# Copyright (c) 2018, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
{% import "shared/macros.jinja2" as macros with context %}

device_type: "{{ device_type }}"

job_name: "{{ build_tag }} - {{ job_name }}"

{% if tags[device_type] %}
tags:
{% for tag in tags[device_type] %}
- {{ tag }}
{% endfor %}
{% endif %}

{% set venv_name = "/tmp/venv" %}

metadata:
    build-url: "{{ build_url }}"
    build-tag: "{{ build_tag }}"
    testplan: "{{ job_name }}"
    mbl-branch: "{{ mbl_branch }}"

priority: medium
visibility: public

timeouts:
  job:
    minutes: 50
  action:
    minutes: 15
  connection:
    minutes: 15

{% if lxc_creation %}
protocols:
  lava-lxc:
    name: "{{ lxc_name }}"
    template: ubuntu
    distribution: ubuntu
    release: xenial
    verbose: true
{% endif %}

{%    set root_partition = root_partition|default(2, true)  %}

{%    set login_prompt = login_prompt|default("mbed-linux-os-(.*) login:", true) %}

{%    set prompts = prompts|default(["root@mbed-linux-os(.*):~#"], true) %}


# Deploy and boot the target
{% include "shared/templates/" + device_type + "-deploy-boot.yaml" with context %}

{% if lxc_creation %}

# Deploy and boot the LXC container
- deploy:
    namespace: lxc
    timeout:
      minutes: 10
    to: lxc
    os: ubuntu
    packages:
    - avahi-utils
    - python3-venv

- boot:
    namespace: lxc
    method: lxc
    timeout:
      minutes: 5
    prompts:
      - "root@{{ lxc_name }}-(.*):/#"
{% endif %}

# Run the testplan
{% block testplan %}
{# This block should contain LAVA test definitions. Those are defined in the
   templates that are extending this file. #}
{% endblock testplan %}

{% if notify_user or notify_emails %}
notify:
    recipients:
    {% if notify_user %}
    - to:
       method: email
       user: "{{ notify_user }}"
    {% endif %}
    {% for email in notify_emails %}
    - to:
       method: email
       email: "{{ email }}"
    {% endfor %}
    criteria:
      status: finished
    verbosity: verbose
{% endif %}

{% if callback_domain and callback_port %}
notify:
    criteria:
       status: finished
    callbacks:
      - url: http://{{ callback_domain }}:{{ callback_port }}/
        method: POST
        dataset: minimal
        content-type: json
{% endif %}